logging:
  level: INFO
  config: classpath:logback-springboot.xml
  path: /web/${spring.application.name}
server:
  port: 80
debug: false
# 跨服务数据合并
merge:
  enabled: true
  guavaCacheNumMaxSize: 1000
  guavaCacheRefreshWriteTime: 10 # min
  guavaCacheRefreshThreadPoolSize: 10
  aop: # 启动注解的方式,自动聚合
    enabled: true
spring:
  application:
    name: newdon
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#    default-property-inclusion: non_null
  datasource:
    name: test
    url: jdbc:mysql://${db.ip:47.98.111.63}:3306/newdon?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: ${db.username:root}
    password: root123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
#  thymeleaf:
#    mode: HTML5
#    encoding: UTF-8
#    cache: false
#    servlet:
#      content-type: text/html
#    prefix: classpath:/templates/
#    suffix: .html
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
mybatis-plus:
  mapper-locations: classpath:mybatis/*.xml
  typeAliasesPackage: com.newdon.entity
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
spring.mvc.favicon.enabled: false
