server:
  port: 80
debug: false
logging:
  config: classpath:logback.xml
spring:
  application:
    name: com.newdon-contract
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#    default-property-inclusion: non_null
  datasource:
    name: test
    url: jdbc:mysql://${db.ip:119.28.180.186}:3306/com.newdon?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: ${db.username:root}
    password: root123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
    prefix: classpath:/templates/
    suffix: .html
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
mybatis-plus:
  mapper-locations: classpath:mybatis/*.xml
  typeAliasesPackage: com.com.newdon.entity
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
spring.mvc.favicon.enabled: false
